// Definicoes dos 6 mapas jogaveis.
// Cada mapa: projecao, recorte geografico, continentes/nacoes jogaveis e
// parametros de geracao (estados, rios, lagos, rotulos, rotas maritimas).
// Terras fora dos continentes incluidos aparecem como "terra estrangeira" (nao simulada).
// minStateKm2: estados menores que isso (na escala do mapa) sao fundidos ao vizinho;
// islandMergeKm: distancia maxima para uma ilha pequena juntar-se a um estado proximo;
// islandKm2: massas de terra menores que isso recebem o terreno "ilha".

export const MAPS = [
  {
    id: 'world',
    name: 'Mapa Mundial',
    description: 'O planeta inteiro: todas as nações disputando continentes e oceanos.',
    projection: { type: 'miller', lon0: 0 },
    bounds: { lonMin: -180, lonMax: 180, latMin: -57, latMax: 83 },
    width: 1800,
    continents: '*',
    include: [],
    exclude: [],
    minNationCells: 3,
    minStateKm2: 12000,
    islandMergeKm: 150,
    islandKm2: 15000,
    riverRank: 5,
    lakeRank: 4,
    featureRank: 1,
    seaRank: 1,
    maxSeaDist: 22,
    maxBridgeDist: 420,
  },
  {
    id: 'americas',
    name: 'Mapa das Américas',
    description: 'Do Alasca à Terra do Fogo: impérios do Novo Mundo.',
    projection: { type: 'miller', lon0: -92 },
    bounds: { lonMin: -172, lonMax: -12, latMin: -56, latMax: 76 },
    width: 1150,
    continents: ['North America', 'South America'],
    include: [],
    exclude: [],
    minNationCells: 4,
    minStateKm2: 5000,
    islandMergeKm: 120,
    islandKm2: 15000,
    riverRank: 7,
    lakeRank: 6,
    featureRank: 2,
    seaRank: 2,
    maxSeaDist: 30,
    maxBridgeDist: 400,
  },
  {
    id: 'europe',
    name: 'Mapa da Europa',
    description: 'Reinos e repúblicas do Atlântico aos Urais.',
    projection: { type: 'lcc', lon0: 15, lat0: 52, lat1: 40, lat2: 64 },
    bounds: { lonMin: -25, lonMax: 60, latMin: 33, latMax: 71.5 },
    width: 1400,
    continents: ['Europe'],
    include: ['TUR', 'CYP', 'CYN', 'GEO', 'ARM', 'AZE'],
    exclude: [],
    minNationCells: 4,
    minStateKm2: 1500,
    islandMergeKm: 60,
    islandKm2: 15000,
    riverRank: 8,
    lakeRank: 7,
    featureRank: 3,
    seaRank: 3,
    maxSeaDist: 40,
    maxBridgeDist: 500,
  },
  {
    id: 'asia-oceania',
    name: 'Mapa da Ásia + Oceania',
    description: 'Impérios asiáticos, arquipélagos do Pacífico e a Oceania.',
    projection: { type: 'miller', lon0: 108 },
    bounds: { lonMin: 25, lonMax: 192, latMin: -48, latMax: 78 },
    width: 1400,
    continents: ['Asia', 'Oceania'],
    include: ['RUS', 'MDV'],
    exclude: [],
    minNationCells: 4,
    minStateKm2: 6000,
    islandMergeKm: 120,
    islandKm2: 15000,
    riverRank: 6,
    lakeRank: 5,
    featureRank: 2,
    seaRank: 2,
    maxSeaDist: 30,
    maxBridgeDist: 450,
  },
  {
    id: 'eurasia',
    name: 'Mapa Europa + Ásia',
    description: 'O supercontinente eurasiático, de Lisboa ao Pacífico.',
    projection: { type: 'miller', lon0: 77 },
    bounds: { lonMin: -25, lonMax: 180, latMin: -11, latMax: 78 },
    width: 1700,
    continents: ['Europe', 'Asia'],
    include: ['MDV'],
    exclude: [],
    minNationCells: 4,
    minStateKm2: 6000,
    islandMergeKm: 120,
    islandKm2: 15000,
    riverRank: 6,
    lakeRank: 5,
    featureRank: 2,
    seaRank: 2,
    maxSeaDist: 26,
    maxBridgeDist: 450,
  },
  {
    id: 'africa',
    name: 'Mapa da África',
    description: 'Do Mediterrâneo ao Cabo da Boa Esperança.',
    projection: { type: 'miller', lon0: 17 },
    bounds: { lonMin: -26, lonMax: 60, latMin: -36, latMax: 38.5 },
    width: 1100,
    continents: ['Africa'],
    include: ['SYC', 'MUS'],
    exclude: [],
    minNationCells: 4,
    minStateKm2: 4000,
    islandMergeKm: 120,
    islandKm2: 15000,
    riverRank: 7,
    lakeRank: 6,
    featureRank: 3,
    seaRank: 3,
    maxSeaDist: 30,
    maxBridgeDist: 400,
  },
];

// Pequenos territorios/dependencias incorporados a uma nacao "mae" quando ela
// existe no mapa (evita micro-nacoes de 1 pixel). null = nunca vira nacao.
export const PARENT = {
  IMN: 'GBR', JEY: 'GBR', GGY: 'GBR', ALD: 'FIN', GIB: 'ESP', HKG: 'CHN', MAC: 'CHN',
  ESB: 'CYP', WSB: 'CYP', CNM: 'CYP', USG: 'CUB', KAB: 'KAZ', KAS: 'IND', BRT: 'SDN',
  BRI: 'URY', SPI: 'CHL', SCR: 'PHL', VAT: 'ITA', SMR: 'ITA', MCO: 'FRA', AND: 'ESP',
  LIE: 'CHE', PGA: null, BJN: null, SER: null, CSI: null, ATC: null, CLP: null, UMI: null,
  HMD: null, IOA: null, SXM: null, MAF: null, BLM: null, ATA: null,
};

export const EXCLUDED_PLACE_CLASSES = new Set(['Scientific station', 'Meteorological Station', 'Historic place']);
